# -*- coding: utf-8 -*-
# Generated by Django 1.11 on 2018-07-19 04:22
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0002_alarminfotb_authgroup_authgrouppermissions_authpermission_authuser_authusergroups_authuseruserpermis'),
    ]

    operations = [
        migrations.CreateModel(
            name='AlarmdetailTb',
            fields=[
                ('alarmsensor_id', models.IntegerField(db_column='AlarmSensor_ID', primary_key=True, serialize=False)),
                ('alarm_sensor_name', models.CharField(db_column='Alarm_sensor_name', max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'alarmdetail_tb',
            },
        ),
        migrations.CreateModel(
            name='AuthorityrecordTb',
            fields=[
                ('login_id', models.CharField(db_column='Login_ID', max_length=1, primary_key=True, serialize=False)),
                ('logpassword', models.CharField(db_column='LogPassword', max_length=1)),
                ('authority', models.SmallIntegerField(db_column='Authority')),
            ],
            options={
                'managed': False,
                'db_table': 'authorityrecord_tb',
            },
        ),
        migrations.CreateModel(
            name='StaffrecordTb',
            fields=[
                ('rfcard_id', models.CharField(db_column='RFCard_ID', max_length=1, primary_key=True, serialize=False)),
                ('staff_name', models.CharField(max_length=1)),
                ('car_num', models.CharField(db_column='Car_num', max_length=1)),
            ],
            options={
                'managed': False,
                'db_table': 'staffrecord_tb',
            },
        ),
    ]
